name: seisml
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _pytorch_select=0.1
  - absl-py=0.9.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.5
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.15.0
  - ca-certificates=2020.4.5.1
  - cachetools=3.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - coverage=5.1
  - cryptography=2.9.2
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.1
  - gettext=0.19.8.1
  - glib=2.64.2
  - google-auth=1.14.2
  - google-auth-oauthlib=0.4.1
  - grpcio=1.27.2
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - h5py=2.10.0
  - hdf5=1.10.5
  - icu=64.2
  - idna=2.9
  - ignite=0.3.0
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - intel-openmp=2020.0
  - ipykernel=5.2.1
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - joblib=0.14.1
  - jpeg=9c
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kiwisolver=1.2.0
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - libsodium=1.0.17
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markdown=3.2.1
  - markupsafe=1.1.1
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mistune=0.8.4
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.1
  - more-itertools=8.2.0
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.1
  - ninja=1.10.0
  - notebook=6.0.3
  - nspr=4.25
  - nss=3.47
  - numpy=1.18.1
  - numpy-base=1.18.1
  - oauthlib=3.0.1
  - olefile=0.46
  - openssl=1.1.1g
  - pandas=1.0.3
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.1.1
  - pip=20.0.2
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - protobuf=3.11.4
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - py=1.8.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pygments=2.6.1
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - pytest=5.4.1
  - pytest-cov=2.8.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.5.0
  - pytz=2019.3
  - pyzmq=19.0.0
  - qt=5.12.5
  - qtconsole=4.7.4
  - qtpy=1.9.0
  - readline=8.0
  - requests=2.23.0
  - requests-oauthlib=1.2.0
  - rsa=4.0
  - scikit-learn=0.22.2.post1
  - scipy=1.4.1
  - seaborn=0.10.0
  - send2trash=1.5.0
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.30.1
  - statsmodels=0.11.1
  - tensorboard=2.1.1
  - tensorboardx=2.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - torchvision=0.6.0
  - tornado=6.0.4
  - traitlets=4.3.3
  - urllib3=1.25.9
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - art==4.6
    - future==0.18.2
    - gin-config==0.3.0
    - lxml==4.5.0
    - obspy==1.2.1
    - packaging==20.3
    - pluggy==0.13.1
    - pycm==2.6
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - sqlalchemy==1.3.16
    - torch-summary==1.2.0
    - tqdm==4.45.0

